FROM prom/prometheus:latest

# Copy configuration files
COPY prometheus.yml /etc/prometheus/prometheus.yml
COPY prometheus-alerts.yml /etc/prometheus/prometheus-alerts.yml

# Set the default command
CMD ["--config.file=/etc/prometheus/prometheus.yml", \
     "--storage.tsdb.path=/prometheus", \
     "--web.console.libraries=/etc/prometheus/console_libraries", \
     "--web.console.templates=/etc/prometheus/consoles", \
     "--storage.tsdb.retention.time=200h", \
     "--web.enable-lifecycle"] 