name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DOCKER_REGISTRY: ghcr.io
  DOCKER_IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: ecommerce_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal
        env:
          ConnectionStrings__DefaultConnection: Host=localhost;Database=ecommerce_test;Username=postgres;Password=postgres

  docker:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Debug Docker Username
        run: echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}"

      - name: Build WebAPI Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/ecommerce-webapi:latest -f src/Presentation/ECommerce.WebAPI/Dockerfile .

      - name: Build AuthServer Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/ecommerce-authserver:latest -f src/Infrastructure/ECommerce.AuthServer/Dockerfile .

      - name: Tag WebAPI image with SHA
        run: docker tag ${{ secrets.DOCKER_USERNAME }}/ecommerce-webapi:latest ${{ secrets.DOCKER_USERNAME }}/ecommerce-webapi:${{ github.sha }}

      - name: Tag AuthServer image with SHA
        run: docker tag ${{ secrets.DOCKER_USERNAME }}/ecommerce-authserver:latest ${{ secrets.DOCKER_USERNAME }}/ecommerce-authserver:${{ github.sha }}

      - name: Push WebAPI Docker image (latest)
        run: docker push ${{ secrets.DOCKER_USERNAME }}/ecommerce-webapi:latest

      - name: Push WebAPI Docker image (SHA)
        run: docker push ${{ secrets.DOCKER_USERNAME }}/ecommerce-webapi:${{ github.sha }}

      - name: Push AuthServer Docker image (latest)
        run: docker push ${{ secrets.DOCKER_USERNAME }}/ecommerce-authserver:latest

      - name: Push AuthServer Docker image (SHA)
        run: docker push ${{ secrets.DOCKER_USERNAME }}/ecommerce-authserver:${{ github.sha }}
